"""empty message

Revision ID: 3e151cd943b6
Revises: 6a30fd650294
Create Date: 2025-05-05 01:22:07.828393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e151cd943b6'
down_revision: Union[str, None] = '6a30fd650294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'company_id')
    # ### end Alembic commands ###
