"""empty message

Revision ID: 98ec6a26eb3c
Revises: d3926d83490d
Create Date: 2025-05-03 19:02:37.808243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98ec6a26eb3c'
down_revision: Union[str, None] = 'd3926d83490d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'department', 'user', ['head_user_id'], ['id'], deferrable=True, use_alter=True)
    op.drop_column('user', 'department_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department_role', postgresql.ENUM('employee', 'manager', 'admin', name='roletype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'department', type_='foreignkey')
    # ### end Alembic commands ###
