"""empty message

Revision ID: d3926d83490d
Revises: 0a935724675d
Create Date: 2025-05-03 19:01:50.080586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3926d83490d'
down_revision: Union[str, None] = '0a935724675d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('company_code', sa.String(length=4), nullable=False),
    sa.Column('admin_code', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_code', 'company', ['company_code'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('head_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['head_user_id'], ['user.id'], deferrable=True, use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('company_role', sa.Enum('employee', 'manager', 'admin', name='roletype'), nullable=False))
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('department_role', sa.Enum('employee', 'manager', 'admin', name='roletype'), nullable=False))
    op.add_column('user', sa.Column('department_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('employee', 'manager', 'admin', name='roletype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.drop_column('user', 'department_id')
    op.drop_column('user', 'department_role')
    op.drop_column('user', 'company_id')
    op.drop_column('user', 'company_role')
    op.drop_table('department')
    op.drop_index('idx_code', table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
